"""Generic single-database configuration."""

"""create_mvp_schema

Revision ID: 2b8511021ee1
Revises: 
Create Date: 2026-08-04 00:07:48.331230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b8511021ee1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('family_members',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_family_members_user_id_name')
    )
    op.create_index('ix_family_members_user_id', 'family_members', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_document_date', 'documents', ['document_date'], unique=False)
    op.create_index('ix_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('ix_documents_family_member_id', 'documents', ['family_member_id'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_index('ix_documents_user_id_created_at', 'documents', ['user_id', 'created_at'], unique=False)
    op.create_table('ai_summaries',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_findings', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_ai_summaries_document_id')
    )
    op.create_table('document_metadata',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_name', sa.String(length=255), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_document_metadata_document_id')
    )
    op.create_index('ix_document_metadata_doctor_name', 'document_metadata', ['doctor_name'], unique=False)
    op.create_index('ix_document_metadata_document_date', 'document_metadata', ['document_date'], unique=False)
    op.create_index('ix_document_metadata_document_type', 'document_metadata', ['document_type'], unique=False)
    op.create_index('ix_document_metadata_hospital_name', 'document_metadata', ['hospital_name'], unique=False)
    op.create_table('embeddings',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('dimensions', sa.Integer(), server_default='1536', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_embeddings_document_id')
    )
    op.create_index('ix_embeddings_model_name', 'embeddings', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_model_name', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_document_metadata_hospital_name', table_name='document_metadata')
    op.drop_index('ix_document_metadata_document_type', table_name='document_metadata')
    op.drop_index('ix_document_metadata_document_date', table_name='document_metadata')
    op.drop_index('ix_document_metadata_doctor_name', table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_table('ai_summaries')
    op.drop_index('ix_documents_user_id_created_at', table_name='documents')
    op.drop_index('ix_documents_user_id', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_family_member_id', table_name='documents')
    op.drop_index('ix_documents_document_type', table_name='documents')
    op.drop_index('ix_documents_document_date', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_family_members_user_id', table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
